all: rn since timely up working-time ydl

rn: rn.go
	go build $<

since: since.go
	go build $<

timely: timely.go
	go build timely.go

up: up.c
	clang -Wall -o up up.c

working-time: working-time.go
	go build working-time.go

ydl: ydl.go
	go build ydl.go
